"""
Writes the fixture that holds the browser's code to this package's behaviour.

    python -m treblewise_ml.parity_fixture

The browser rebuilds three things in TypeScript: the rectifying warp, the
bilinear sampling into the square, and the heatmap decoder. If any of them
drifts from Python, a model that passed evaluation here reads different tips in
the app. The fixture is synthetic — a made-up camera, made-up tips, a gradient
image — because it is committed to a public repository.

Output: packages/core/tests/fixtures/tips-parity.json
"""

from __future__ import annotations

import json
from pathlib import Path

import cv2
import numpy as np

from .board import RECT_SIZE, board_to_rect, image_to_rect, solve_homography
from .dataset import encode_targets
from .decode import decode

OUT = Path(__file__).resolve().parents[2] / "packages" / "core" / "tests" / "fixtures" / "tips-parity.json"

TO_IMAGE = np.array([[0.9, -0.2, 360.0], [0.05, -1.1, 640.0], [1e-4, -3e-4, 1.0]])
CALIBRATION_BOARD = np.array([[0, 170], [170, 0], [0, -170], [-170, 0]], dtype=np.float64)


def main() -> None:
    image_points = (TO_IMAGE @ np.c_[CALIBRATION_BOARD, np.ones(4)].T).T
    image_points = image_points[:, :2] / image_points[:, 2:]
    to_board = solve_homography(image_points, CALIBRATION_BOARD)

    # A small warp of a small image, sampled exactly as training does.
    rng = np.random.default_rng(7)
    small = rng.integers(0, 256, (48, 64, 3), dtype=np.uint8)
    small_warp = np.array([[1.3, 0.2, -5.0], [-0.1, 1.1, 3.0], [0.001, -0.0005, 1.0]])
    warped = cv2.warpPerspective(small, small_warp, (40, 30), flags=cv2.INTER_LINEAR)

    tips = np.array([[100.3, 200.9], [300.0, 50.25], [256.0, 256.0], [140.6, 380.1]])
    heat, offset, _ = encode_targets(tips)
    heat[0, 20, 20] = 0.2  # below the threshold: must not be reported
    cells = np.argwhere(heat[0] > 1e-4)
    decoded = decode(heat, offset)

    fixture = {
        "note": "Generated by python -m treblewise_ml.parity_fixture. Synthetic data only.",
        "rect": {"size": RECT_SIZE, "boardToRect": board_to_rect().flatten().tolist()},
        "toBoard": to_board.flatten().tolist(),
        "imageToRect": image_to_rect(to_board).flatten().tolist(),
        "sampling": {
            "width": 64,
            "height": 48,
            "rgb": small.flatten().tolist(),  # row-major HWC, BGR order as OpenCV holds it
            "warp": small_warp.flatten().tolist(),
            "outWidth": 40,
            "outHeight": 30,
            "expected": warped.flatten().tolist(),
        },
        "decode": {
            "heat": [[int(y), int(x), float(heat[0, y, x])] for y, x in cells],
            "offset": [[int(y), int(x), float(offset[0, y, x]), float(offset[1, y, x])] for y, x in np.argwhere(offset.any(axis=0))],
            "expected": [
                {"x": t.x, "y": t.y, "confidence": t.confidence, "board": list(t.board), "label": t.hit.label()} for t in decoded
            ],
        },
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(fixture), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size / 1000:.0f} kB), {len(decoded)} tips")


if __name__ == "__main__":
    main()
